// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf_engine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfAggValT struct {
	_         structs.HostLayout
	Packets   uint64
	FirstTsNs uint64
	LastTsNs  uint64
	LastLatUs uint64
	LastPid   uint32
	LastTask  [16]int8
	LastSaddr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	LastDaddr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	LastSport    uint16
	LastDport    uint16
	LastProtocol uint8
	LastIsIpv6   uint8
	Pad          [2]uint8
	_            [4]byte
}

type BpfFilterV4T struct {
	_        structs.HostLayout
	Sip      uint32
	Dip      uint32
	Sport    uint16
	Dport    uint16
	Protocol uint8
	_        [3]byte
}

type BpfFilterV6T struct {
	_        structs.HostLayout
	Sip      [16]uint8
	Dip      [16]uint8
	Sport    uint16
	Dport    uint16
	Protocol uint8
	_        [1]byte
}

type BpfLatKeyT struct {
	_     structs.HostLayout
	Saddr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Daddr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Sport     uint16
	Dport     uint16
	Protocol  uint8
	IsIpv6    uint8
	Direction uint8
	Pad       uint8
}

type BpfLatValT struct {
	_    structs.HostLayout
	TsNs uint64
	Pid  uint32
	Task [16]int8
	_    [4]byte
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	Inet6RecvmsgFunc     *ebpf.ProgramSpec `ebpf:"inet6_recvmsg_func"`
	Inet6SendmsgFunc     *ebpf.ProgramSpec `ebpf:"inet6_sendmsg_func"`
	InetRecvmsgFunc      *ebpf.ProgramSpec `ebpf:"inet_recvmsg_func"`
	InetSendmsgFunc      *ebpf.ProgramSpec `ebpf:"inet_sendmsg_func"`
	Ip6FinishOutputFunc  *ebpf.ProgramSpec `ebpf:"ip6_finish_output_func"`
	Ip6InputFunc         *ebpf.ProgramSpec `ebpf:"ip6_input_func"`
	IpFinishOutputFunc   *ebpf.ProgramSpec `ebpf:"ip_finish_output_func"`
	IpLocalDeliverFunc   *ebpf.ProgramSpec `ebpf:"ip_local_deliver_func"`
	NetDevStartXmitFunc  *ebpf.ProgramSpec `ebpf:"net_dev_start_xmit_func"`
	TcpDropFunc          *ebpf.ProgramSpec `ebpf:"tcp_drop_func"`
	TcpDropReasonFunc    *ebpf.ProgramSpec `ebpf:"tcp_drop_reason_func"`
	TcpRecvmsgFunc       *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_func"`
	TcpSendmsgFunc       *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_func"`
	TraceKfreeSkb        *ebpf.ProgramSpec `ebpf:"trace_kfree_skb"`
	TraceNetifReceiveSkb *ebpf.ProgramSpec `ebpf:"trace_netif_receive_skb"`
	UdpRecvmsgFunc       *ebpf.ProgramSpec `ebpf:"udp_recvmsg_func"`
	UdpSendmsgFunc       *ebpf.ProgramSpec `ebpf:"udp_sendmsg_func"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	AggMap              *ebpf.MapSpec `ebpf:"agg_map"`
	FiveTupleFilterIpv4 *ebpf.MapSpec `ebpf:"five_tuple_filter_ipv4"`
	FiveTupleFilterIpv6 *ebpf.MapSpec `ebpf:"five_tuple_filter_ipv6"`
	StartLink           *ebpf.MapSpec `ebpf:"start_link"`
	StartTranslink      *ebpf.MapSpec `ebpf:"start_translink"`
	StartTransnetwork   *ebpf.MapSpec `ebpf:"start_transnetwork"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	UNUSED_aggValT *ebpf.VariableSpec `ebpf:"UNUSED_agg_val_t"`
	UNUSED_eventT  *ebpf.VariableSpec `ebpf:"UNUSED_event_t"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	AggMap              *ebpf.Map `ebpf:"agg_map"`
	FiveTupleFilterIpv4 *ebpf.Map `ebpf:"five_tuple_filter_ipv4"`
	FiveTupleFilterIpv6 *ebpf.Map `ebpf:"five_tuple_filter_ipv6"`
	StartLink           *ebpf.Map `ebpf:"start_link"`
	StartTranslink      *ebpf.Map `ebpf:"start_translink"`
	StartTransnetwork   *ebpf.Map `ebpf:"start_transnetwork"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.AggMap,
		m.FiveTupleFilterIpv4,
		m.FiveTupleFilterIpv6,
		m.StartLink,
		m.StartTranslink,
		m.StartTransnetwork,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	UNUSED_aggValT *ebpf.Variable `ebpf:"UNUSED_agg_val_t"`
	UNUSED_eventT  *ebpf.Variable `ebpf:"UNUSED_event_t"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	Inet6RecvmsgFunc     *ebpf.Program `ebpf:"inet6_recvmsg_func"`
	Inet6SendmsgFunc     *ebpf.Program `ebpf:"inet6_sendmsg_func"`
	InetRecvmsgFunc      *ebpf.Program `ebpf:"inet_recvmsg_func"`
	InetSendmsgFunc      *ebpf.Program `ebpf:"inet_sendmsg_func"`
	Ip6FinishOutputFunc  *ebpf.Program `ebpf:"ip6_finish_output_func"`
	Ip6InputFunc         *ebpf.Program `ebpf:"ip6_input_func"`
	IpFinishOutputFunc   *ebpf.Program `ebpf:"ip_finish_output_func"`
	IpLocalDeliverFunc   *ebpf.Program `ebpf:"ip_local_deliver_func"`
	NetDevStartXmitFunc  *ebpf.Program `ebpf:"net_dev_start_xmit_func"`
	TcpDropFunc          *ebpf.Program `ebpf:"tcp_drop_func"`
	TcpDropReasonFunc    *ebpf.Program `ebpf:"tcp_drop_reason_func"`
	TcpRecvmsgFunc       *ebpf.Program `ebpf:"tcp_recvmsg_func"`
	TcpSendmsgFunc       *ebpf.Program `ebpf:"tcp_sendmsg_func"`
	TraceKfreeSkb        *ebpf.Program `ebpf:"trace_kfree_skb"`
	TraceNetifReceiveSkb *ebpf.Program `ebpf:"trace_netif_receive_skb"`
	UdpRecvmsgFunc       *ebpf.Program `ebpf:"udp_recvmsg_func"`
	UdpSendmsgFunc       *ebpf.Program `ebpf:"udp_sendmsg_func"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.Inet6RecvmsgFunc,
		p.Inet6SendmsgFunc,
		p.InetRecvmsgFunc,
		p.InetSendmsgFunc,
		p.Ip6FinishOutputFunc,
		p.Ip6InputFunc,
		p.IpFinishOutputFunc,
		p.IpLocalDeliverFunc,
		p.NetDevStartXmitFunc,
		p.TcpDropFunc,
		p.TcpDropReasonFunc,
		p.TcpRecvmsgFunc,
		p.TcpSendmsgFunc,
		p.TraceKfreeSkb,
		p.TraceNetifReceiveSkb,
		p.UdpRecvmsgFunc,
		p.UdpSendmsgFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
