version: "3.9"

services:
  locator:
    build: .                   # 或使用 image: packetscope-tracer
    container_name: packetscope-tracer
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/history:/app/data/history
      - ./data/geoip/GeoLite2-City.mmdb:/app/data/geoip/GeoLite2-City.mmdb
      - ./data/geoip/GeoLite2-ASN.mmdb:/app/data/geoip/GeoLite2-ASN.mmdb
      - ./data/threat/risky_ips.json:/app/data/threat/risky_ips.json
