// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package tcxprober

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcxProberPacketMetadata struct {
	_          structs.HostLayout
	Direction  uint64
	Timestamp  uint64
	Netifidx   uint64
	Payloadlen uint64
	Payload    [6144]uint8
}

// loadTcxProber returns the embedded CollectionSpec for tcxProber.
func loadTcxProber() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcxProberBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcxProber: %w", err)
	}

	return spec, err
}

// loadTcxProberObjects loads tcxProber and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcxProberObjects
//	*tcxProberPrograms
//	*tcxProberMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcxProberObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcxProber()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcxProberSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxProberSpecs struct {
	tcxProberProgramSpecs
	tcxProberMapSpecs
	tcxProberVariableSpecs
}

// tcxProberProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxProberProgramSpecs struct {
	TcxEgress  *ebpf.ProgramSpec `ebpf:"tcx_egress"`
	TcxIngress *ebpf.ProgramSpec `ebpf:"tcx_ingress"`
}

// tcxProberMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxProberMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	MetadataBuffer *ebpf.MapSpec `ebpf:"metadata_buffer"`
}

// tcxProberVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxProberVariableSpecs struct {
}

// tcxProberObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcxProberObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxProberObjects struct {
	tcxProberPrograms
	tcxProberMaps
	tcxProberVariables
}

func (o *tcxProberObjects) Close() error {
	return _TcxProberClose(
		&o.tcxProberPrograms,
		&o.tcxProberMaps,
	)
}

// tcxProberMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcxProberObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxProberMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	MetadataBuffer *ebpf.Map `ebpf:"metadata_buffer"`
}

func (m *tcxProberMaps) Close() error {
	return _TcxProberClose(
		m.Events,
		m.MetadataBuffer,
	)
}

// tcxProberVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcxProberObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxProberVariables struct {
}

// tcxProberPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcxProberObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxProberPrograms struct {
	TcxEgress  *ebpf.Program `ebpf:"tcx_egress"`
	TcxIngress *ebpf.Program `ebpf:"tcx_ingress"`
}

func (p *tcxProberPrograms) Close() error {
	return _TcxProberClose(
		p.TcxEgress,
		p.TcxIngress,
	)
}

func _TcxProberClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcxprober_bpfeb.o
var _TcxProberBytes []byte
